[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd client && npm install",
  "cd server && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "cp -r client/dist server/public"
]

[start]
cmd = "cd server && node src/index.js"
